import tkinter

WIDTH, HEIGHT = 800, 800
ROWS, COLS = 8, 8
SQUARE_SIZE = WIDTH // COLS
BORDER = 1

FIRST_COLOR = "#edf4f5"
SECOND_COLOR = "#9e2f44"
OUTLINE_COLOR = "black"
FIRST_TILE_COLOR = "#d95b55"
SECOND_TILE_COLOR = "#59c7cf"
HIGHLIGHTED_COLOR = "#e2e394"
